### ISSUE TITLE
Tests failing using latest solc. 

### ISSUE THREAD

**Issue by androlo** [androlo/standard-contracts#3]
Need to go over and update.

**Comment by androlo** [comment]
memory pointer not correct in `ByteSlice`. Fixed. Will be in next patch, along with the new bytes 'toXXX` methods. Future-proofing a bit as well.

**Comment by androlo** [comment]
Memory layout of structs must have changed.

**Comment by androlo** [comment]
no, it's the 'bnot, not, iszero' thing.

**Comment by stevenroose** [comment]
I'm thinking of creating a byte buffer library using slice. Is this error fixed?

**Comment by androlo** [comment]
yes, just forgot to remove issue
